/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UKTemplateField.h"

@class NSMutableArray, UKArrayTemplateField;

@interface UKArrayItemTemplateField : UKTemplateField
{
    NSMutableArray *fields;
    UKArrayTemplateField *owningArray;
}

+ (void)load;
- (id)initWithSettingsDictionary:(id)arg1 owner:(id)arg2;
- (void)dealloc;
- (void)readFromData:(id)arg1 offset:(int *)arg2;
- (void)writeToData:(id)arg1 offset:(int *)arg2;
- (id)plistRepresentation;
- (id)fieldValueForKey:(id)arg1;
- (BOOL)canHaveSubFields;
- (int)countSubFields;
- (id)subFieldAtIndex:(int)arg1;
- (void)addSubField:(id)arg1;
- (BOOL)isSelectable;
- (void)delete:(id)arg1;
- (void)addNewField:(id)arg1;

@end

