/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface UKPluginRegistry : NSObject
{
    NSMutableArray *plugins;
    NSMutableDictionary *pluginPaths;
    BOOL instantiate;
}

+ (id)sharedRegistry;
- (id)init;
- (void)dealloc;
- (void)loadPluginsOfType:(id)arg1;
- (void)loadPluginsFromPath:(id)arg1 ofType:(id)arg2;
- (id)loadPluginForPath:(id)arg1;
- (id)loadedPlugins;
- (BOOL)instantiate;
- (void)setInstantiate:(BOOL)arg1;

@end

