/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "UKTemplateFieldOverridableMethods-Protocol.h"
#import "UKTemplateFieldProtocol-Protocol.h"

@class NSDictionary, NSDocument;

@interface UKTemplateField : NSObject <UKTemplateFieldProtocol, UKTemplateFieldOverridableMethods>
{
    NSDictionary *settings;
    NSDocument *owningDocument;
}

+ (void)registerTemplateFieldClass:(Class)arg1 forType:(id)arg2;
+ (void)registerForDefaultName;
+ (id)fieldWithSettingsDictionary:(id)arg1;
- (id)initWithSettingsDictionary:(id)arg1;
- (void)dealloc;
- (void)readFromData:(id)arg1 offset:(int *)arg2;
- (void)loadDefaults;
- (void)writeToData:(id)arg1 offset:(int *)arg2;
- (void)addToArray:(id)arg1;
- (id)plistRepresentation;
- (void)controlTextDidChange:(id)arg1;
- (void)dataChanged:(id)arg1;
- (void)setOwningDocument:(id)arg1;
- (id)owningDocument;
- (id)fieldValueForKey:(id)arg1;
- (id)fieldValue;
- (BOOL)canHaveSubFields;
- (int)countSubFields;
- (id)subFieldAtIndex:(int)arg1;
- (id)objectForSettingsKey:(id)arg1;
- (BOOL)isBigEndian;
- (BOOL)isLittleEndian;
- (void)updateDocumentGUI;
- (void)reportChangeOfUnknownKey:(id)arg1;
- (BOOL)fieldValueIsEditableForKey:(id)arg1;
- (BOOL)isSelectable;

@end

