/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol UKTemplateFieldOverridableMethods
- (void)readFromData:(id)arg1 offset:(int *)arg2;
- (void)writeToData:(id)arg1 offset:(int *)arg2;
- (id)plistRepresentation;
@end

